sudo: false
language: python
cache: pip
services:
  - postgresql
python:
  - "3.6"
install:
  - "pip install pipenv"
  - "pipenv install"
  - "pipenv install --dev"
before_script:
  - psql -c 'CREATE DATABASE tryonhistory;' -U postgres
  - psql -c 'CREATE USER test;' -U postgres
  - psql -c 'ALTER USER test CREATEDB;' -U postgres
script:
  - cd server/tryonhistory && pipenv run python3 manage.py test
