# Generated by Django 2.0 on 2017-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20171206_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tryonhistory',
            name='date_tried_on',
            field=models.DateTimeField(),
        ),
    ]
