# Generated by Django 2.0 on 2017-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20171209_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
    ]
