# Generated by Django 2.0 on 2017-12-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20171209_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonhistory',
            name='date_purchased',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
