# Generated by Django 2.0 on 2017-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_tryonhistory_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
